version: '3'
services:

  mysql:
    image: mysql:latest
    container_name: racha-cafe
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: assinatura
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${USER_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

volumes:
  mysql_data:
