version: '3'
services:
  assinatura_microservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql_db
    networks:
      - td_soft

  mysql_db:
    image: mysql:latest
    container_name: racha-cafe
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: assinatura
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${USER_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - td_soft

networks:
  td_soft:
    driver: bridge
